/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ringcard;


import com.mycompany.ringcard.data.dataUsuarios;
import java.sql.Connection;
import com.mycompany.ringcard.data.MovimientoDAO;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public int idUsuarioLogueado;

 
    public home(int id) {
        initComponents();
        
        this.idUsuarioLogueado = id;
        
        // (Opcional) Puedes imprimir un mensaje en consola para comprobar que llegó bien
        System.out.println("Sesión iniciada. ID del usuario: " + this.idUsuarioLogueado);
        this.setLocationRelativeTo(null);
        
        dataUsuarios du = new dataUsuarios();
        Connection con = du.conectar();

        MovimientoDAO dao = new MovimientoDAO(con);
        ResultSet rs =
        dao.obtenerTodosLosMovimientos(idUsuarioLogueado);
        llenarTabla(rs);
    }
    
    private void llenarTabla(ResultSet rs) {

    try {

        DefaultTableModel modelo =
                (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        while(rs.next()) {

            modelo.addRow(new Object[]{

                rs.getDate("fecha_movimiento"),
                rs.getString("tarjeta"),
                rs.getString("tipo_movimiento"),
                rs.getString("concepto"),
                rs.getDouble("monto")

            });
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPrincipal = new javax.swing.JPanel();
        panprincipal = new javax.swing.JPanel();
        ContenedorGeneralCyD = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CBMostrar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContentPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panprincipal.setBackground(new java.awt.Color(64, 60, 60));
        panprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContenedorGeneralCyD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        CBMostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar Todo", "Ingresos", "Egresos", "Solo Credito", "Solo Debito" }));
        CBMostrar.addActionListener(this::CBMostrarActionPerformed);

        jTable1.setBackground(new java.awt.Color(64, 64, 64));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Targeta", "Tipo", "Concepto", "Monto"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        ContenedorGeneralCyD.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 720));

        panprincipal.add(ContenedorGeneralCyD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 720));

        jPanel3.setBackground(new java.awt.Color(64, 64, 64));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Debito");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Credito");

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setText("jLabel3");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(67, 67, 67))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        panprincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 330, 720));

        ContentPrincipal.add(panprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jMenu1.setText("Opciones");
        jMenu1.setPreferredSize(new java.awt.Dimension(70, 22));
        jMenu1.addActionListener(this::jMenu1ActionPerformed);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IcardmovB.png"))); // NOI18N
        jMenuItem1.setText("Movimientos");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(146, 31));
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icardgenB.png"))); // NOI18N
        jMenuItem2.setText("General");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tarjeta");
        jMenu2.setPreferredSize(new java.awt.Dimension(60, 22));

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IcardB.png"))); // NOI18N
        jMenuItem3.setText("TarjetasC");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IcardB.png"))); // NOI18N
        jMenuItem4.setText("TarjetasD");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMostrarActionPerformed
    dataUsuarios du = new dataUsuarios();
    Connection con = du.conectar();

    MovimientoDAO dao = new MovimientoDAO(con);

    String opcion = CBMostrar.getSelectedItem().toString();

    System.out.println("Seleccionado: " + opcion);

    switch(opcion) {

        case "Mostrar Todo":
            llenarTabla(
                dao.obtenerTodosLosMovimientos(idUsuarioLogueado)
            );
            break;

        case "Ingresos":
            llenarTabla(
                dao.obtenerIngresos(idUsuarioLogueado)
            );
            break;

        case "Egresos":
            llenarTabla(
                dao.obtenerEgresos(idUsuarioLogueado)
            );
            break;

        case "Solo Credito":
            llenarTabla(
                dao.obtenerSoloCredito(idUsuarioLogueado)
            );
            break;

        case "Solo Debito":
            llenarTabla(
                dao.obtenerSoloDebito(idUsuarioLogueado)
            );
            break;
    }

    }//GEN-LAST:event_CBMostrarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Te lleva al panel de Movimientos
        PanleMovimientos panmov = new PanleMovimientos(idUsuarioLogueado);
        panmov.setSize(ContentPrincipal.getSize());
        panmov.setLocation(0,0);
        

        ContentPrincipal.removeAll();
        ContentPrincipal.add(panmov,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280,720));
        ContentPrincipal.revalidate();
        ContentPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Te lleva a el panel de home donde vez todas las estadisticas de todas las cards
        panprincipal.setSize(ContentPrincipal.getSize());
        panprincipal.setLocation(0,0);
        ContentPrincipal.removeAll();
        ContentPrincipal.add(panprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,1280,720));
        ContentPrincipal.revalidate();
        ContentPrincipal.repaint();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         TarjetasAddC tac = new TarjetasAddC(idUsuarioLogueado);
        tac.setSize(ContentPrincipal.getSize());
        tac.setLocation(0,0);
        

        ContentPrincipal.removeAll();
        ContentPrincipal.add(tac,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280,720));
        ContentPrincipal.revalidate();
        ContentPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         TarjetasAddD tad = new TarjetasAddD(idUsuarioLogueado);
        tad.setSize(ContentPrincipal.getSize());
        tad.setLocation(0,0);
        

        ContentPrincipal.removeAll();
        ContentPrincipal.add(tad,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280,720));
        ContentPrincipal.revalidate();
        ContentPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        //FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new home(0).setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBMostrar;
    private javax.swing.JPanel ContenedorGeneralCyD;
    private javax.swing.JPanel ContentPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panprincipal;
    // End of variables declaration//GEN-END:variables

    
}
