/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;
import com.mycompany.ringcard.clases.usuarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Lg extends javax.swing.JPanel {

    /**
     * Creates new form Lg
     */
    public Lg() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg1.setBackground(new java.awt.Color(255, 255, 255));
        lg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Correo");
        lg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 70, -1));

        txt2.setForeground(new java.awt.Color(153, 153, 153));
        txt2.setText("********");
        txt2.addActionListener(this::txt2ActionPerformed);
        lg1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        lg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 100, -1));

        txt1.setForeground(new java.awt.Color(153, 153, 153));
        txt1.setText("Ingresa el correo");
        txt1.addActionListener(this::txt1ActionPerformed);
        lg1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, -1));

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(this::BtnIngresarActionPerformed);
        lg1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 100, 40));

        add(lg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt1ActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        usuarios o=new usuarios();
        try{
            o.setEmail(txt1.getText());
            o.setPass(txt2.getText());
            if (o.autenticarUsuario()) {
    JOptionPane.showMessageDialog(null, "Inicio correcto");
    
    
    int id = o.getId_usuario(); 


    home ventanaHome = new home(id);
    
    
    ventanaHome.setVisible(true);
  
    java.awt.Window ventanaPadre = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (ventanaPadre != null) {
        ventanaPadre.dispose();
    }
    
} else {
    JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
}
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lg1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
