/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.awt.BorderLayout;

/**
 *
 * @author DELL
 */
public class Lg extends javax.swing.JPanel {

    /**
     * Creates new form Lg
     */
    public Lg() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Correo");
        lg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        lg1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setText("Password");
        lg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, -1));

        jTextField2.setText("jTextField1");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        lg1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton1.setText("jButton1");
        lg1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 200, -1, -1));

        jLabel3.setText("Registrar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        lg1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 30));

        add(lg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        rg rg=new rg();
        
        rg.setSize(222,318);
        rg.setLocation(0,0);
        lg1.removeAll();
        lg1.add(lg1, BorderLayout.CENTER);
        lg1.revalidate();
lg1.repaint();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        rg rg=new rg();
        
        rg.setSize(222,318);
        rg.setLocation(0,0);
        lg1.removeAll();
        lg1.add(lg1, BorderLayout.CENTER);
        lg1.revalidate();
lg1.repaint();
    }//GEN-LAST:event_jLabel3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel lg1;
    // End of variables declaration//GEN-END:variables
}
