/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;

import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author DELL
 */
public class MovimientosAddC extends javax.swing.JPanel {

    private int idUsuarioLog;
    private int idTarjeta;
    private JPanel panelPadre; // Referencia al panel principal
    private String nombreBanco; // Guardamos el nombre del banco

    // Actualizamos el constructor
    public MovimientosAddC(int idUsuarioLogueado, int idTarjetaSeleccionada, String nombreBanco, JPanel padre) {
        initComponents();
        this.idUsuarioLog = idUsuarioLogueado;
        this.idTarjeta = idTarjetaSeleccionada;
        this.nombreBanco = nombreBanco;
        this.panelPadre = padre;

        // 1. Actualizamos el Label
        jLabel1.setText("Tarjeta a hacer el cambio: " + this.nombreBanco);

        // --- ESTILO VISUAL DE LA PANTALLA ---
        aplicarEstilosModernos();

        try {
            MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
            mascaraFecha.setPlaceholderCharacter('_');
            mascaraFecha.install(jFormattedTextField1);
        } catch (ParseException ex) {
            System.err.println("Error en el formato de la fecha: " + ex.getMessage());
        }
    }
// ... resto de tu código generado

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(938, 628));

        jLabel1.setText("Tarjeta a hacer el cambio:");

        jButton1.setText("volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel2.setText("Tipo Movimeinto");

        jLabel3.setText("Fecha Movimeinto");

        jLabel4.setText("Concepto");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel5.setText("Monto");

        jSpinner1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setText("Agregar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addActionListener(this::jFormattedTextField1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        volverAtras();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:çç

        String tipoMovimiento = jComboBox1.getSelectedItem().toString().toLowerCase(); // "ingreso" o "egreso"
        String fechaStr = jFormattedTextField1.getText();
        String concepto = jTextField1.getText();

        Object valorSpinner = jSpinner1.getValue();
        double monto = 0;
        if (valorSpinner instanceof Number) {
            monto = ((Number) valorSpinner).doubleValue();
        }

        if (monto <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero.");
            return;
        }

        java.sql.Date fechaSQL = null;
        try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fecha = sdf.parse(fechaStr);
            fechaSQL = new java.sql.Date(fecha.getTime());
        } catch (ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa el formato DD/MM/YYYY");
            return;
        }

        java.sql.Connection cx = null;
        java.sql.PreparedStatement psInsert = null;
        java.sql.PreparedStatement psUpdate = null;

        try {
            cx = new com.mycompany.ringcard.data.dataMovimientos().getConnection();
            cx.setAutoCommit(false); // Transacción segura

            // 1. Insertar en movimientos_credito
            String sqlInsert = "INSERT INTO movimientos_credito (id_cardcredito, tipo_movimiento, fecha_movimiento, concepto, monto) VALUES (?, ?, ?, ?, ?)";
            psInsert = cx.prepareStatement(sqlInsert);
            psInsert.setInt(1, this.idTarjeta);
            psInsert.setString(2, tipoMovimiento);
            psInsert.setDate(3, fechaSQL);
            psInsert.setString(4, concepto);
            psInsert.setDouble(5, monto);
            psInsert.executeUpdate();

            // 2. Lógica inversa para el crédito (la deuda sube o baja)
            String sqlUpdate = "";
            if (tipoMovimiento.equals("egreso")) { // Si compro algo, mi deuda sube (+)
                sqlUpdate = "UPDATE cardscredito SET saldo_actual = saldo_actual + ? WHERE id_cardcredito = ?";
            } else if (tipoMovimiento.equals("ingreso")) { // Si abono a la tarjeta, mi deuda baja (-)
                sqlUpdate = "UPDATE cardscredito SET saldo_actual = saldo_actual - ? WHERE id_cardcredito = ?";
            }

            psUpdate = cx.prepareStatement(sqlUpdate);
            psUpdate.setDouble(1, monto);
            psUpdate.setInt(2, this.idTarjeta);
            psUpdate.executeUpdate();

            // Confirmar cambios
            cx.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Movimiento de crédito registrado con éxito.");
            volverAtras();

        } catch (Exception ex) {
            if (cx != null) {
                try {
                    cx.rollback();
                } catch (Exception r) {
                    r.printStackTrace();
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el movimiento: " + ex.getMessage());
        } finally {
            try {
                if (psInsert != null) {
                    psInsert.close();
                }
                if (psUpdate != null) {
                    psUpdate.close();
                }
                if (cx != null) {
                    cx.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void aplicarEstilosModernos() {
        // 1. Fondo oscuro para que combine con el resto de la app
        this.setBackground(new java.awt.Color(45, 45, 45));

        // 2. Fuente moderna para las etiquetas
        java.awt.Font fuenteEtiquetas = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
        java.awt.Color colorTexto = java.awt.Color.WHITE;

        // Estilizar todas las etiquetas
        javax.swing.JLabel[] etiquetas = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5};
        for (javax.swing.JLabel label : etiquetas) {
            label.setFont(fuenteEtiquetas);
            label.setForeground(colorTexto);
        }

        // 3. Estilizar el JComboBox (Desplegable)
        jComboBox1.setBackground(new java.awt.Color(64, 64, 64));
        jComboBox1.setForeground(colorTexto);
        jComboBox1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jComboBox1.setFocusable(false); // Quitar borde punteado

        // 4. Estilizar los campos de texto
        java.awt.Color fondoInputs = new java.awt.Color(64, 64, 64);

        jFormattedTextField1.setBackground(fondoInputs);
        jFormattedTextField1.setForeground(colorTexto);
        jFormattedTextField1.setCaretColor(colorTexto); // Color del cursor titilante
        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)),
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding interno
        ));

        jTextField1.setBackground(fondoInputs);
        jTextField1.setForeground(colorTexto);
        jTextField1.setCaretColor(colorTexto);
        jTextField1.setBorder(jFormattedTextField1.getBorder()); // Mismo borde
        jTextField1.setText(""); // Limpiar el texto por defecto

        // Estilizar Spinner (es un poco más complejo porque tiene botones adentro)
        jSpinner1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        javax.swing.JComponent editor = jSpinner1.getEditor();
        if (editor instanceof javax.swing.JSpinner.DefaultEditor) {
            javax.swing.JSpinner.DefaultEditor spinnerEditor = (javax.swing.JSpinner.DefaultEditor) editor;
            spinnerEditor.getTextField().setBackground(fondoInputs);
            spinnerEditor.getTextField().setForeground(colorTexto);
            spinnerEditor.getTextField().setCaretColor(colorTexto);
        }

        // 5. Estilizar los botones inferiores
        java.awt.Font fuenteBotones = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);

        // Botón "volver" (Gris claro)
        jButton1.setBackground(new java.awt.Color(100, 100, 100));
        jButton1.setForeground(java.awt.Color.WHITE);
        jButton1.setFont(fuenteBotones);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);

        // Botón "Guardar" (Verde Material)
        jButton2.setBackground(new java.awt.Color(67, 160, 71));
        jButton2.setForeground(java.awt.Color.WHITE);
        jButton2.setFont(fuenteBotones);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void volverAtras() {
        java.awt.Container contenedor = this.getParent();
        if (contenedor != null) {
            contenedor.remove(this);

            if (panelPadre instanceof PanleMovimientos) {
                ((PanleMovimientos) panelPadre).cargarMovimientos();
            }

            contenedor.revalidate();
            contenedor.repaint();
        }
    }

}
