/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;

import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author DELL
 */
public class MovimientosAddC extends javax.swing.JPanel {

    private int idUsuarioLog;
    private int idTarjeta;
    private javax.swing.JPanel panelPadre;

    // Actualizamos el constructor para recibir más datos
    public MovimientosAddC(int idUsuarioLogueado, int idTarjetaSeleccionada, String nombreBanco, javax.swing.JPanel padre) {
        initComponents();
        this.idUsuarioLog = idUsuarioLogueado;
        this.idTarjeta = idTarjetaSeleccionada;
        this.panelPadre = padre;

        // Actualizamos el Label con el nombre del banco
        jLabel1.setText("Tarjeta a hacer el cambio: " + nombreBanco);

        try {
            MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
            mascaraFecha.setPlaceholderCharacter('_');
            mascaraFecha.install(jFormattedTextField1);
        } catch (ParseException ex) {
            System.err.println("Error en el formato de la fecha: " + ex.getMessage());
        }
    }
// ... resto de tu código generado

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(938, 628));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tarjeta a hacer el cambio:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 150, -1));

        jButton1.setText("volver");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 140, -1));

        jLabel2.setText("Tipo Movimeinto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel3.setText("Fecha Movimeinto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabel4.setText("Concepto");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, -1));

        jLabel5.setText("Monto");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jSpinner1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 140, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        volverAtras();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:çç

        String tipoMovimiento = jComboBox1.getSelectedItem().toString().toLowerCase(); // "ingreso" o "egreso"
        String fechaStr = jFormattedTextField1.getText();
        String concepto = jTextField1.getText();

        Object valorSpinner = jSpinner1.getValue();
        double monto = 0;
        if (valorSpinner instanceof Number) {
            monto = ((Number) valorSpinner).doubleValue();
        }

        if (monto <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero.");
            return;
        }

        java.sql.Date fechaSQL = null;
        try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fecha = sdf.parse(fechaStr);
            fechaSQL = new java.sql.Date(fecha.getTime());
        } catch (ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa el formato DD/MM/YYYY");
            return;
        }

        java.sql.Connection cx = null;
        java.sql.PreparedStatement psInsert = null;
        java.sql.PreparedStatement psUpdate = null;

        try {
            cx = new com.mycompany.ringcard.data.dataMovimientos().getConnection();
            cx.setAutoCommit(false); // Transacción segura

            // 1. Insertar en movimientos_credito
            String sqlInsert = "INSERT INTO movimientos_credito (id_cardcredito, tipo_movimiento, fecha_movimiento, concepto, monto) VALUES (?, ?, ?, ?, ?)";
            psInsert = cx.prepareStatement(sqlInsert);
            psInsert.setInt(1, this.idTarjeta);
            psInsert.setString(2, tipoMovimiento);
            psInsert.setDate(3, fechaSQL);
            psInsert.setString(4, concepto);
            psInsert.setDouble(5, monto);
            psInsert.executeUpdate();

            // 2. Lógica inversa para el crédito (la deuda sube o baja)
            String sqlUpdate = "";
            if (tipoMovimiento.equals("egreso")) { // Si compro algo, mi deuda sube (+)
                sqlUpdate = "UPDATE cardscredito SET saldo_actual = saldo_actual + ? WHERE id_cardcredito = ?";
            } else if (tipoMovimiento.equals("ingreso")) { // Si abono a la tarjeta, mi deuda baja (-)
                sqlUpdate = "UPDATE cardscredito SET saldo_actual = saldo_actual - ? WHERE id_cardcredito = ?";
            }

            psUpdate = cx.prepareStatement(sqlUpdate);
            psUpdate.setDouble(1, monto);
            psUpdate.setInt(2, this.idTarjeta);
            psUpdate.executeUpdate();

            // Confirmar cambios
            cx.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Movimiento de crédito registrado con éxito.");
            volverAtras();

        } catch (Exception ex) {
            if (cx != null) {
                try {
                    cx.rollback();
                } catch (Exception r) {
                    r.printStackTrace();
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el movimiento: " + ex.getMessage());
        } finally {
            try {
                if (psInsert != null) {
                    psInsert.close();
                }
                if (psUpdate != null) {
                    psUpdate.close();
                }
                if (cx != null) {
                    cx.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void volverAtras() {
        java.awt.Container contenedor = this.getParent();
        if (contenedor != null) {
            contenedor.remove(this);

            if (panelPadre instanceof PanleMovimientos) {
                ((PanleMovimientos) panelPadre).cargarMovimientos();
            }

            contenedor.revalidate();
            contenedor.repaint();
        }
    }

}
