/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;

import com.mycompany.ringcard.models.Usuario;
import com.mycompany.ringcard.reutilizables.BotonRedondo;
import com.mycompany.ringcard.reutilizables.PanelRedondeado;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class rg extends javax.swing.JPanel {

    /**
     * Creates new form rg
     */
    public rg() {
        initComponents();
        new com.mycompany.ringcard.controllers.RegistroController(
            this, 
            new com.mycompany.ringcard.dao.impl.UsuarioDAOImpl()
        );
    }

    // --- AGREGA ESTOS GETTERS AL FINAL DE TU CLASE ---
    public javax.swing.JTextField getTxtn() { return txtn; }
    public javax.swing.JTextField getTxtap() { return txtap; }
    public javax.swing.JTextField getTxtam() { return txtam; }
    public javax.swing.JTextField getTxtem() { return txtem; }
    public javax.swing.JTextField getTxtpas() { return txtpas; }
    public javax.swing.JTextField getTxttel() { return txttel; }
    public javax.swing.JButton getBtnRegistrar() { return jButton1; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelRedondeado();
        jLabel1 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtam = new javax.swing.JTextField();
        txtem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new BotonRedondo("Ingresar");
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(20, 20, 0));
        setPreferredSize(new java.awt.Dimension(640, 728));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setForeground(new java.awt.Color(200, 200, 200));
        jPanel1.setMaximumSize(new java.awt.Dimension(168, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(168, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 525));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IpersonN1.png"))); // NOI18N
        jLabel1.setText("Nombre:");

        txtn.setBackground(new java.awt.Color(217, 217, 217));
        txtn.setForeground(new java.awt.Color(0, 0, 0));
        txtn.setText("ingresa el nombre");
        txtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnFocusGained(evt);
            }
        });
        txtn.addActionListener(this::txtnActionPerformed);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IpersonN1.png"))); // NOI18N
        jLabel2.setText("Apellido Paterno:");

        txtap.setBackground(new java.awt.Color(217, 217, 217));
        txtap.setForeground(new java.awt.Color(0, 0, 0));
        txtap.setText("Ingresa Apellido");
        txtap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapFocusGained(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IpersonN1.png"))); // NOI18N
        jLabel3.setText("Apellido Materno:");

        txtam.setBackground(new java.awt.Color(217, 217, 217));
        txtam.setForeground(new java.awt.Color(0, 0, 0));
        txtam.setText("Ingresa Apellido");
        txtam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtamFocusGained(evt);
            }
        });

        txtem.setBackground(new java.awt.Color(217, 217, 217));
        txtem.setForeground(new java.awt.Color(0, 0, 0));
        txtem.setText("Ingresa tu Gmail");
        txtem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemFocusGained(evt);
            }
        });
        txtem.addActionListener(this::txtemActionPerformed);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IpasswN.png"))); // NOI18N
        jLabel4.setText("Contraseña:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImailN.png"))); // NOI18N
        jLabel5.setText("Email:");

        txtpas.setBackground(new java.awt.Color(217, 217, 217));
        txtpas.setForeground(new java.awt.Color(0, 0, 0));
        txtpas.setText("Ingresa Contraseña");
        txtpas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasFocusGained(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IphoneN.png"))); // NOI18N
        jLabel6.setText("Telefono:");

        txttel.setBackground(new java.awt.Color(217, 217, 217));
        txttel.setForeground(new java.awt.Color(0, 0, 0));
        txttel.setText("55-5555-5555");
        txttel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelFocusGained(evt);
            }
        });
        txttel.addActionListener(this::txttelActionPerformed);
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(59, 56, 62));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.setBorderPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(80, 27));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 27));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IpersonN.png"))); // NOI18N
        jLabel7.setText("Registrarse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
        //txtn
    }//GEN-LAST:event_txtnActionPerformed

    private void txttelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyTyped
        // TODO add your handling code here:
        if (txttel.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txttelKeyTyped

    private void txtemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemActionPerformed

    private void txtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnFocusGained
        // TODO add your handling code here:
        if (txtn.getText().equals("ingresa el nombre")) {
            txtn.setText("");
            txtn.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtnFocusGained

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void txtapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapFocusGained
        // TODO add your handling code here:
        if (txtap.getText().equals("Ingresa Apellido")) {
            txtap.setText("");
            txtap.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtapFocusGained

    private void txtamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamFocusGained
        // TODO add your handling code here:
        if (txtam.getText().equals("Ingresa Apellido")) {
            txtam.setText("");
            txtam.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtamFocusGained

    private void txtpasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasFocusGained
        // TODO add your handling code here:
        if (txtpas.getText().equals("Ingresa Contraseña")) {
            txtpas.setText("");
            txtpas.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtpasFocusGained

    private void txtemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemFocusGained
        // TODO add your handling code here:
        if (txtem.getText().equals("Ingresa tu Gmail")) {
            txtem.setText("");
            txtem.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtemFocusGained

    private void txttelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelFocusGained
        // TODO add your handling code here:
        if (txttel.getText().equals("55-5555-5555")) {
            txttel.setText("");
            txttel.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txttelFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtem;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtpas;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
