/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;

import com.mycompany.ringcard.clases.usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class rg extends javax.swing.JPanel {

    /**
     * Creates new form rg
     */
    public rg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtam = new javax.swing.JTextField();
        txtem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(168, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(168, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtn.setText("ingresa el nombre");
        txtn.addActionListener(this::txtnActionPerformed);
        jPanel1.add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido Paterno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        txtap.setText("Ingresa Apelledo");
        jPanel1.add(txtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 260, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido Materno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtam.setText("Ingresa Apellido");
        jPanel1.add(txtam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, -1));

        txtem.setText("Ingresa tu Gmail");
        jPanel1.add(txtem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 260, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Gmail:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        txtpas.setText("********");
        jPanel1.add(txtpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 260, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        txttel.setText("********");
        jPanel1.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 474));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        usuarios o = new usuarios();
        try{
            o.setNombre(txtn.getText());
            o.setAp(txtap.getText());
            o.setAm(txtam.getText());
            o.setEmail(txtem.getText());
            o.setPass(txtpas.getText());
            o.setTelefono(Integer.parseInt(txttel.getText()));
            
            if(o.insertarUsuario()){
                JOptionPane.showMessageDialog(null, "Registrado correctamente");
                
      
                
                
                java.awt.Container contenedorPadre = this.getParent();
                
                if (contenedorPadre != null) {
                    
                    contenedorPadre.removeAll();
                    
                   
                    Lg panelLogin = new Lg();
                    panelLogin.setSize(contenedorPadre.getSize());
                    panelLogin.setLocation(0, 0);
                    
                    contenedorPadre.add(panelLogin);
                    
                    contenedorPadre.revalidate();
                    contenedorPadre.repaint();
                }
                // ---------------------------------------------
                // ---------------------------------------------
                
            }else{
                JOptionPane.showMessageDialog(null, "Datos invalidos");
            }
            
        }catch(Exception e){
            e.printStackTrace(); // Es buena práctica imprimir el error en consola si algo falla
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtem;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtpas;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
