/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;
import com.mycompany.ringcard.clases.TarjetasCred;
import com.mycompany.ringcard.data.dataTarjetascred;
import java.sql.Date;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
/**
 *
 * @author drako
 */
public class TarjetasAddC extends javax.swing.JPanel {

    /**
     * Creates new form TarjetasAdd
     */
    public int idUser;
    public TarjetasAddC(int id) {
        initComponents();
        this.idUser=id;
        try {
  
    MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
    
   
    mascaraFecha.setPlaceholderCharacter('_');
    
   
    mascaraFecha.install(jFormattedTextField1);
    
} catch (ParseException ex) {
    System.err.println("Error en el formato de la fecha: " + ex.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, 70));

        jLabel1.setText("Dia de Corte");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel2.setText("Banco");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel3.setText("PorcentajeDeInteres");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("Estado");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel5.setText("SaldoActual");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel6.setText("LimiteCredito");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
        add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pagado", "vencido", "espera" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel7.setText("FechaVencimiento");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel8.setText("CantidadAbonada");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
        TarjetasCred tCred = new TarjetasCred();

        tCred.setBanco(jTextField1.getText());
        
        // Se extraen los nuevos valores numéricos usando Number para evitar errores de casteo
        tCred.setCantidadab(((Number) jSpinner5.getValue()).doubleValue());
        tCred.setPctinteres(((Number) jSpinner4.getValue()).intValue());

        String textoFecha = jFormattedTextField1.getText();
        try {
            java.text.SimpleDateFormat formatoEntrada = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fechaParseada = formatoEntrada.parse(textoFecha);
            tCred.setFecha_vencimiento(new java.sql.Date(fechaParseada.getTime()));
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa la fecha completa en formato DD/MM/YYYY (ej. 06/06/2026).", "Error en la Fecha", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        tCred.setEstado(jComboBox1.getSelectedItem().toString());
        tCred.setSaldo_actual(((Number) jSpinner1.getValue()).doubleValue());
        tCred.setLimite_credito(((Number) jSpinner2.getValue()).doubleValue());
        tCred.setFecha_corte(((Number) jSpinner3.getValue()).intValue());
        tCred.setId_usuario(idUser);

        if (tCred.insertarTarjetac()) {
            JOptionPane.showMessageDialog(this, "Tarjeta de crédito agregada con éxito.");
            home ventanaHome = new home(idUser);
            ventanaHome.setVisible(true);
            
            java.awt.Window ventanaPadre = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (ventanaPadre != null) {
                ventanaPadre.dispose();
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
