/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;
import com.mycompany.ringcard.clases.TarjetasCred;
import com.mycompany.ringcard.data.dataTarjetascred;
import java.sql.Date;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
/**
 *
 * @author drako
 */
public class TarjetasAddC extends javax.swing.JPanel {

    /**
     * Creates new form TarjetasAdd
     */
    public TarjetasAddC() {
        initComponents();
        try {
  
    MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
    
   
    mascaraFecha.setPlaceholderCharacter('_');
    
   
    mascaraFecha.install(jFormattedTextField1);
    
} catch (ParseException ex) {
    System.err.println("Error en el formato de la fecha: " + ex.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, -1, -1));

        jTextField3.setText("jTextField3");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jTextField4.setText("jTextField4");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jTextField5.setText("jTextField5");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jTextField6.setText("jTextField6");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                TarjetasCred tCred = new TarjetasCred();
             // Asume un ID de usuario activo en tu sesión
              
                tCred.setBanco(jTextField1.getText());
                tCred.setFecha_vencimiento(Date.valueOf(jFormattedTextField1.getText())); 
                tCred.setEstado(jTextField3.getText());
                tCred.setSaldo_actual(Integer.parseInt(jTextField4.getText()));
                tCred.setLimite_credito(Integer.parseInt(jTextField5.getText()));
                tCred.setFecha_corte(Integer.parseInt(jTextField6.getText()));

                dataTarjetascred dao = new dataTarjetascred();
                if (dao.insertarTarjetac(tCred)) {
                    JOptionPane.showMessageDialog(this, "Tarjeta de crédito agregada con éxito.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Revisa los datos ingresados. Fechas en formato YYYY-MM-DD y montos numéricos.", "Error de formato", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
