/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ringcard;

import com.mycompany.ringcard.clases.TarjetasCred;
import com.mycompany.ringcard.clases.TarjetasDeb;
import com.mycompany.ringcard.data.dataTarjetascred;
import com.mycompany.ringcard.data.dataTarjetasdeb;
import java.sql.Date;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author drako
 */
public class TarjetasAddD extends javax.swing.JPanel {

    /**
     * Creates new form TarjetasAddD
     */
    public int iduser;
    public TarjetasAddD(int id) {
        initComponents();
        this.iduser=id;
        try {
  
    MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
    
   
    mascaraFecha.setPlaceholderCharacter('_');
    
   
    mascaraFecha.install(jFormattedTextField1);
    
} catch (ParseException ex) {
    System.err.println("Error en el formato de la fecha: " + ex.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 40));

        jLabel1.setText("Bancp");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setText("Fecha");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Saldo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                TarjetasDeb tCred = new TarjetasDeb();
             // Asume un ID de usuario activo en tu sesión
              
                tCred.setBanco(jTextField1.getText());
                String textoFecha = jFormattedTextField1.getText();

try {
    // 2. Le decimos a Java que el usuario escribe en formato Día/Mes/Año
    java.text.SimpleDateFormat formatoEntrada = new java.text.SimpleDateFormat("dd/MM/yyyy");
    
    // 3. Convertimos el texto a una fecha normal de Java
    java.util.Date fechaParseada = formatoEntrada.parse(textoFecha);
    
    // 4. Transformamos esa fecha al formato estricto que requiere SQL y la guardamos en tu objeto
    tCred.setFecha_vencimiento(new java.sql.Date(fechaParseada.getTime()));
    
} catch (java.text.ParseException e) {
    // Si el usuario escribe letras o algo que no es una fecha válida, mostramos error y detenemos el proceso
    JOptionPane.showMessageDialog(this, "Por favor ingresa la fecha completa en formato DD/MM/YYYY (ej. 06/06/2026).", "Error en la Fecha", JOptionPane.ERROR_MESSAGE);
    return; // Este return evita que el código siga intentando guardar en la base de datos
}
                tCred.setSaldo_actual((int) jSpinner1.getValue());
                
tCred.setId_usuario(iduser);
                dataTarjetasdeb dao = new dataTarjetasdeb();
                if (dao.insertarTarjetad(tCred)) {
                    JOptionPane.showMessageDialog(this, "Tarjeta de Debito agregada con éxito.");
                    home ventanaHome = new home(iduser);
                    
                    // 2. Hacemos visible el home
                    ventanaHome.setVisible(true);
                    
                    // 3. Cerramos la ventana actual
                    java.awt.Window ventanaPadre = javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (ventanaPadre != null) {
                        ventanaPadre.dispose();
                    } 
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Revisa los datos ingresados. Fechas en formato YYYY-MM-DD y montos numéricos.", "Error de formato", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
